---
extends:
  - 'airbnb-base'
  - 'plugin:jsdoc/recommended'
root: true
env:
  browser: 1
  jquery: 1
  es6: 0
rules:
  consistent-return:
    - 0
  no-underscore-dangle:
    - 0
  max-nested-callbacks:
    - 1
    - 3
  import/no-mutable-exports:
    - 1
  no-plusplus:
    - 1
    - allowForLoopAfterthoughts: true
  no-param-reassign:
    - 0
  no-prototype-builtins:
    - 0
  brace-style:
    - error
    - stroustrup
  no-unused-vars:
    - 1
  no-var:
    - 1
  object-shorthand:
    - error
    - always
