---
options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
      - 'breakpoint'
      - 'mq'

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: false
  single-line-per-selector: 2

  # Disallows
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
      - '*font-family'
      - '*height'
      - 'interpolation-mode'
      - '*margin-left'
      - '*vertical-align'
      - '*width'
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  function-name-format: 1
  id-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    - style: stroustrup
    - allow-single-line: false
  clean-import-paths: 2
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 4
  property-sort-order: 0
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
